class defaultUserActions;
class DefaultEventhandlers;
class CfgPatches
{
	class AIF_all
	{
		units[]=
		{
			"aif_flag",
			"aif_support_MG",
			"aif_rifleman",
			"aif_riflemanAK103",
			"aif_riflemanM4",
			"aif_riflemanGL",
			"aif_riflemanGLM4",
			"aif_specialist_Ex",
			"aif_support_AT",
			"aif_support_rpg26",
			"aif_support_AA",
			"aif_medic",
			"aif_oficial3",
			"aif_oficial2",
			"aif_oficial",
			"aif_TeamLeader",
			"aif_driver",
			"aif_sniper",
			"aif_UAV",
			"aif_mortar",
			"aif_TeamLeader_G",
			"aif_support_rpg26_G",
			"aif_medic_G",
			"aif_rifleman_G",
			"aif_apc",
			"aif_t72b",
			"aif_zu234v",
			"aif_truck",
			"aif_truck_ural",
			"aif_armed",
			"aif_offroad",
			"aif_offroad2",
			"aif_Static_M2",
			"aif_Static_M2_MiniTripod",
			"aif_Static_Mk19_TriPod",
			"aif_Static_AT",
			"aif_Static_AA",
			"aif_Static_mortar",
			"aif_car"
		};
		weapons[]={};
		author[]=
		{
			"Segen"
		};
		authorUrl="http://www.clanusml.net/iwar.html";
		text="Made by Segen";
		versionDesc="Irregular Warfare";
		version="0.1.7";
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"rhs_main"
		};
	};
};
class CfgFactionClasses
{
	class usml_aif
	{
		icon="aif_all\data\ui\usml_aif_faction.paa";
		flag="aif_all\data\ui\aif_flag.paa";
		displayName="Armed Islamic Front";
		priority=14;
		side=2;
	};
};
class cfgVehicles
{
	class Flag_us_f;
	class aif_Flag: Flag_us_f
	{
		_generalMacro="Flag_us_f";
		scope=2;
		scopeCurator=2;
		side=2;
		accuracy=1000;
		faction="default";
		displayName="Flag (Armed Islamic Front)";
		class EventHandlers
		{
			init="(_this select 0) setFlagTexture ""\aif_all\data\aif_flag.paa""";
		};
	};
	class B_G_Soldier_F;
	class aif_TeamLeader_G: B_G_Soldier_F
	{
		_generalMacro="  B_G_Soldier_F ";
		scope=2;
		side=2;
		faction="usml_aif";
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_NATO",
			"NoGlasses"
		};
		faceType="Man_A3";
		genericNames="TakistaniMen";
		displayName="Team Leader Elite";
		author="segen";
		camouflage=0.60000002;
		sensitivity=3.5;
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		model="\A3\characters_F\civil\c_poor";
		uniformClass="aif_uni_dig_g";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\data\aif_uni_dig_g.paa"
		};
		backpack="";
		weapons[]=
		{
			"Binocular",
			"rhs_weap_m4_m203",
			"hgun_rook40_f",
			"Throw",
			"put"
		};
		respawnweapons[]=
		{
			"Binocular",
			"rhs_weap_m4_m203",
			"hgun_rook40_f",
			"Throw",
			"put"
		};
		respawnmagazines[]=
		{
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"aif_uni_vest",
			"H_Cap_blk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ACE_NVG_Gen1",
			"acc_flashlight",
			"ItemGPS"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"aif_uni_vest",
			"H_Cap_blk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ACE_NVG_Gen1",
			"acc_flashlight",
			"ItemGPS"
		};
		class EventHandlers
		{
			init="(_this select 0) execVM ""\aif_all\script\ejecutores.sqf""";
		};
	};
	class aif_support_rpg26_G: B_G_Soldier_F
	{
		_generalMacro="  B_G_Soldier_F ";
		scope=2;
		side=2;
		faction="usml_aif";
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_NATO",
			"NoGlasses"
		};
		faceType="Man_A3";
		genericNames="TakistaniMen";
		displayName="AT Soldier RPG26 Elite";
		author="segen";
		icon="iconManAT";
		nakedUniform="U_BasicBody";
		model="\A3\characters_F\civil\c_poor";
		uniformClass="aif_uni_tig_g2";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\data\aif_uni_tig_g2.paa"
		};
		backpack="";
		weapons[]=
		{
			"Binocular",
			"rhs_weap_ak74m_folded",
			"rhs_weap_rpg26",
			"Throw",
			"put"
		};
		respawnweapons[]=
		{
			"Binocular",
			"rhs_weap_ak74m_folded",
			"rhs_weap_rpg26",
			"Throw",
			"put"
		};
		respawnmagazines[]=
		{
			"rhs_30Rnd_545x39_AK",
			"rhs_30Rnd_545x39_AK",
			"rhs_30Rnd_545x39_AK",
			"rhs_30Rnd_545x39_AK",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		magazines[]=
		{
			"rhs_30Rnd_545x39_AK",
			"rhs_30Rnd_545x39_AK",
			"rhs_30Rnd_545x39_AK",
			"rhs_30Rnd_545x39_AK",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		items[]=
		{
			"FirstAidKit"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"aif_uni_vest2",
			"H_ShemagOpen_khk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"aif_uni_vest2",
			"H_ShemagOpen_khk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		class EventHandlers
		{
			init="(_this select 0) execVM ""\aif_all\script\ejecutores.sqf""";
		};
	};
	class aif_medic_G: B_G_Soldier_F
	{
		_generalMacro="  B_G_Soldier_F ";
		scope=2;
		side=2;
		faction="usml_aif";
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_NATO",
			"NoGlasses"
		};
		faceType="Man_A3";
		genericNames="TakistaniMen";
		displayName="Medic Elite";
		author="segen";
		camouflage=0.60000002;
		sensitivity=3.5;
		icon="iconManMedic";
		nakedUniform="U_BasicBody";
		model="\A3\characters_F\civil\c_poor";
		uniformClass="aif_uni_tig_g";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\data\aif_uni_tig_g.paa"
		};
		backpack="aif_Bag_Medic";
		weapons[]=
		{
			"Binocular",
			"rhs_weap_ak74m_2mag_npz",
			"hgun_rook40_f",
			"Throw",
			"put"
		};
		respawnweapons[]=
		{
			"Binocular",
			"rhs_weap_ak74m_2mag_npz",
			"Throw",
			"put"
		};
		respawnmagazines[]=
		{
			"rhs_30Rnd_545x39_AK",
			"rhs_30Rnd_545x39_AK",
			"rhs_30Rnd_545x39_AK",
			"rhs_30Rnd_545x39_AK",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		magazines[]=
		{
			"rhs_30Rnd_545x39_AK",
			"rhs_30Rnd_545x39_AK",
			"rhs_30Rnd_545x39_AK",
			"rhs_30Rnd_545x39_AK",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"aif_uni_vest",
			"H_Cap_blk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"aif_uni_vest",
			"H_Cap_blk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		class EventHandlers
		{
			init="(_this select 0) execVM ""\aif_all\script\ejecutores.sqf""";
		};
	};
	class aif_rifleman_G: B_G_Soldier_F
	{
		_generalMacro="  B_G_Soldier_F ";
		scope=2;
		side=2;
		faction="usml_aif";
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_NATO",
			"NoGlasses"
		};
		faceType="Man_A3";
		genericNames="TakistaniMen";
		displayName="Rifleman Elite";
		author="segen";
		camouflage=0.60000002;
		sensitivity=3.5;
		icon="iconMan";
		nakedUniform="U_BasicBody";
		model="\A3\characters_F\civil\c_poor";
		uniformClass="aif_uni_dig_g2";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\data\aif_uni_dig_g2.paa"
		};
		backpack="";
		weapons[]=
		{
			"Binocular",
			"rhs_weap_akm",
			"hgun_rook40_f",
			"Throw",
			"put"
		};
		respawnweapons[]=
		{
			"Binocular",
			"rhs_weap_akm",
			"hgun_rook40_f",
			"Throw",
			"put"
		};
		respawnmagazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		magazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"aif_uni_vest",
			"H_Cap_blk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"aif_uni_vest",
			"H_Cap_blk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		class EventHandlers
		{
			init="(_this select 0) execVM ""\aif_all\script\ejecutores.sqf""";
		};
	};
	class aif_TeamLeader: B_G_Soldier_F
	{
		_generalMacro="  B_G_Soldier_F ";
		scope=2;
		side=2;
		faction="usml_aif";
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_NATO",
			"NoGlasses"
		};
		faceType="Man_A3";
		genericNames="TakistaniMen";
		displayName="Team Leader";
		author="segen";
		camouflage=0.60000002;
		sensitivity=3.5;
		icon="iconManLeader";
		nakedUniform="U_BasicBody";
		model="\A3\characters_F\civil\c_poor";
		uniformClass="aif_uni_tig_w3";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\data\aif_uni_tig_w3.paa"
		};
		backpack="";
		weapons[]=
		{
			"Binocular",
			"rhs_weap_akm_gp25",
			"hgun_rook40_f",
			"Throw",
			"put"
		};
		respawnweapons[]=
		{
			"Binocular",
			"rhs_weap_akm_gp25",
			"hgun_rook40_f",
			"Throw",
			"put"
		};
		respawnmagazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_VOG25",
			"rhs_VOG25",
			"rhs_VOG25",
			"rhs_VOG25",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		magazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_VOG25",
			"rhs_VOG25",
			"rhs_VOG25",
			"rhs_VOG25",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"aif_uni_vest",
			"H_Cap_blk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"aif_uni_vest",
			"H_Cap_blk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		class EventHandlers
		{
			init="(_this select 0) execVM ""\aif_all\script\regulares.sqf""";
		};
	};
	class aif_support_AT: B_G_Soldier_F
	{
		_generalMacro="  B_G_Soldier_F ";
		scope=2;
		side=2;
		faction="usml_aif";
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_NATO",
			"NoGlasses"
		};
		faceType="Man_A3";
		genericNames="TakistaniMen";
		displayName="AT Soldier RPG-7";
		author="segen";
		icon="iconManAT";
		nakedUniform="U_BasicBody";
		model="\A3\characters_F\civil\c_poor";
		uniformClass="aif_uni_tig_w2";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\data\aif_uni_tig_w2.paa"
		};
		backpack="aif_Bag_AT";
		weapons[]=
		{
			"Binocular",
			"rhs_weap_akm",
			"rhs_weap_rpg7_pgo",
			"Throw",
			"put"
		};
		respawnweapons[]=
		{
			"Binocular",
			"rhs_weap_akm",
			"rhs_weap_rpg7_pgo",
			"Throw",
			"put"
		};
		respawnmagazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		magazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		items[]=
		{
			"FirstAidKit"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"aif_uni_vest2",
			"H_ShemagOpen_khk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"aif_uni_vest2",
			"H_ShemagOpen_khk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		class EventHandlers
		{
			init="(_this select 0) execVM ""\aif_all\script\regulares.sqf""";
		};
	};
	class b_Kitbag_mcamo;
	class aif_Bag_AT: b_Kitbag_mcamo
	{
		class TransportMagazines
		{
			class _xx_RPG32_F
			{
				magazine="rhs_rpg7_PG7VL_mag";
				count=3;
			};
			class _xx_rhs_30Rnd_762x39mm
			{
				magazine="rhs_30Rnd_762x39mm";
				count=2;
			};
		};
	};
	class aif_support_rpg26: B_G_Soldier_F
	{
		_generalMacro="  B_G_Soldier_F ";
		scope=2;
		side=2;
		faction="usml_aif";
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_NATO",
			"NoGlasses"
		};
		faceType="Man_A3";
		genericNames="TakistaniMen";
		displayName="AT Soldier RPG-26";
		author="segen";
		icon="iconManAT";
		nakedUniform="U_BasicBody";
		model="\A3\characters_F\civil\c_poor";
		uniformClass="aif_uni_wood_w3";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\data\aif_uni_wood_w3.paa"
		};
		backpack="";
		weapons[]=
		{
			"Binocular",
			"rhs_weap_ak74m_folded",
			"rhs_weap_rpg26",
			"Throw",
			"put"
		};
		respawnweapons[]=
		{
			"Binocular",
			"rhs_weap_ak74m_folded",
			"rhs_weap_rpg26",
			"Throw",
			"put"
		};
		respawnmagazines[]=
		{
			"rhs_30Rnd_545x39_AK",
			"rhs_30Rnd_545x39_AK",
			"rhs_30Rnd_545x39_AK",
			"rhs_30Rnd_545x39_AK",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		magazines[]=
		{
			"rhs_30Rnd_545x39_AK",
			"rhs_30Rnd_545x39_AK",
			"rhs_30Rnd_545x39_AK",
			"rhs_30Rnd_545x39_AK",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		items[]=
		{
			"FirstAidKit"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"aif_uni_vest2",
			"H_ShemagOpen_khk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"aif_uni_vest2",
			"H_ShemagOpen_khk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		class EventHandlers
		{
			init="(_this select 0) execVM ""\aif_all\script\regulares.sqf""";
		};
	};
	class aif_support_AA: B_G_Soldier_F
	{
		_generalMacro="  B_G_Soldier_F ";
		scope=2;
		side=2;
		faction="usml_aif";
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_NATO",
			"NoGlasses"
		};
		faceType="Man_A3";
		genericNames="TakistaniMen";
		displayName="AA Soldier Igla";
		author="segen";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		model="\A3\characters_F\civil\c_poor";
		uniformClass="aif_uni_mc";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\data\aif_uni_mc.paa"
		};
		backpack="aif_Bag_AA";
		weapons[]=
		{
			"Binocular",
			"rhs_weap_akm",
			"rhs_weap_igla",
			"Throw",
			"put"
		};
		respawnweapons[]=
		{
			"Binocular",
			"rhs_weap_akm",
			"rhs_weap_igla",
			"Throw",
			"put"
		};
		respawnmagazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		magazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		items[]=
		{
			"FirstAidKit"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"aif_uni_vest2",
			"H_ShemagOpen_khk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"aif_uni_vest2",
			"H_ShemagOpen_khk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		class EventHandlers
		{
			init="(_this select 0) execVM ""\aif_all\script\regulares.sqf""";
		};
	};
	class B_TacticalPack_mcamo;
	class aif_Bag_AA: B_TacticalPack_mcamo
	{
		class TransportMagazines
		{
			class _xx_9k38_rocket
			{
				magazine="rhs_mag_9k38_rocket";
				count=2;
			};
			class _xx_rhs_30Rnd_762x39mm
			{
				magazine="rhs_30Rnd_762x39mm";
				count=2;
			};
		};
	};
	class aif_medic: B_G_Soldier_F
	{
		_generalMacro="  B_G_Soldier_F ";
		scope=2;
		side=2;
		faction="usml_aif";
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_NATO",
			"NoGlasses"
		};
		faceType="Man_A3";
		genericNames="TakistaniMen";
		displayName="Medic";
		author="segen";
		camouflage=0.60000002;
		sensitivity=3.5;
		icon="iconManMedic";
		nakedUniform="U_BasicBody";
		model="\A3\characters_F\civil\c_poor";
		uniformClass="aif_uni_3c_des2";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\data\aif_uni_3c_des2.paa"
		};
		backpack="aif_Bag_Medic";
		weapons[]=
		{
			"Binocular",
			"rhs_weap_ak74m_2mag_npz",
			"hgun_rook40_f",
			"Throw",
			"put"
		};
		respawnweapons[]=
		{
			"Binocular",
			"rhs_weap_ak74m_2mag_npz",
			"Throw",
			"put"
		};
		respawnmagazines[]=
		{
			"rhs_30Rnd_545x39_AK",
			"rhs_30Rnd_545x39_AK",
			"rhs_30Rnd_545x39_AK",
			"rhs_30Rnd_545x39_AK",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		magazines[]=
		{
			"rhs_30Rnd_545x39_AK",
			"rhs_30Rnd_545x39_AK",
			"rhs_30Rnd_545x39_AK",
			"rhs_30Rnd_545x39_AK",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"aif_uni_vest",
			"H_Cap_blk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"aif_uni_vest",
			"H_Cap_blk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		class EventHandlers
		{
			init="(_this select 0) execVM ""\aif_all\script\regulares.sqf""";
		};
	};
	class B_FieldPack_cbr;
	class aif_Bag_Medic: B_FieldPack_cbr
	{
		class TransportItems
		{
			class _xx_ACE_fieldDressing
			{
				name="ACE_fieldDressing";
				count=10;
			};
			class _xx_ACE_packingBandage
			{
				name="ACE_packingBandage";
				count=10;
			};
			class _xx_ACE_elasticBandage
			{
				name="ACE_elasticBandage";
				count=10;
			};
			class _xx_ACE_morphine
			{
				name="ACE_morphine";
				count=10;
			};
			class _xx_ACE_epinephrine
			{
				name="ACE_epinephrine";
				count=10;
			};
			class _xx_ACE_quikclot
			{
				name="ACE_quikclot";
				count=10;
			};
			class _xx_ACE_tourniquet
			{
				name="ACE_tourniquet";
				count=5;
			};
			class _xx_ACE_bloodIV_500
			{
				name="ACE_bloodIV_500";
				count=2;
			};
			class _xx_ACE_bloodIV_250
			{
				name="ACE_bloodIV_250";
				count=2;
			};
			class _xx_ACE_personalAidKit
			{
				name="ACE_personalAidKit";
				count=4;
			};
		};
	};
	class aif_UAV: B_G_Soldier_F
	{
		_generalMacro="   B_G_Soldier_F  ";
		scope=2;
		side=2;
		faction="usml_aif";
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_NATO",
			"NoGlasses"
		};
		faceType="Man_A3";
		genericNames="TakistaniMen";
		displayName="UAV Operator";
		author="segen";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		model="\A3\characters_F\civil\c_poor";
		uniformClass="aif_uni_3c_des";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\data\aif_uni_3c_des.paa"
		};
		backpack="O_UAV_01_backpack_F";
		weapons[]=
		{
			"Binocular",
			"rhs_weap_akm",
			"hgun_rook40_f",
			"Throw",
			"put"
		};
		respawnweapons[]=
		{
			"Binocular",
			"rhs_weap_akm",
			"hgun_rook40_f",
			"Throw",
			"put"
		};
		respawnmagazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		magazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"aif_uni_vest",
			"optic_MRCO",
			"acc_flashlight",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"O_UavTerminal"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"aif_uni_vest2",
			"optic_MRCO",
			"acc_flashlight",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			" O_UavTerminal"
		};
		class EventHandlers
		{
			init="(_this select 0) execVM ""\aif_all\script\regulares.sqf""";
		};
	};
	class aif_Driver: B_G_Soldier_F
	{
		_generalMacro="  B_G_Soldier_F   ";
		scope=2;
		side=2;
		faction="usml_aif";
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_NATO",
			"NoGlasses"
		};
		faceType="Man_A3";
		genericNames="TakistaniMen";
		displayName="Crew Member";
		author="segen";
		nakedUniform="U_BasicBody";
		icon="iconManEngineer";
		model="\A3\characters_F\civil\c_poor";
		uniformClass="aif_uni_wood_w2";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\data\aif_uni_wood_w2.paa"
		};
		backpack="";
		weapons[]=
		{
			"Binocular",
			"rhs_weap_ak103_npz",
			"hgun_rook40_f",
			"Throw",
			"put"
		};
		respawnweapons[]=
		{
			"Binocular",
			"rhs_weap_ak103_npz",
			"hgun_rook40_f",
			"Throw",
			"put"
		};
		respawnmagazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		magazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"aif_uni_vest2",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemGPS",
			"ItemRadio"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"aif_uni_vest2",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemGPS",
			"ItemRadio"
		};
		class EventHandlers
		{
			init="(_this select 0) execVM ""\aif_all\script\tripulante.sqf""";
		};
	};
	class aif_riflemanGL: B_G_Soldier_F
	{
		_generalMacro="  B_G_Soldier_F ";
		scope=2;
		side=2;
		faction="usml_aif";
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_NATO",
			"NoGlasses"
		};
		faceType="Man_A3";
		genericNames="TakistaniMen";
		displayName="Grenadier";
		author="segen";
		camouflage=0.60000002;
		sensitivity=3.5;
		icon="iconManExplosive";
		nakedUniform="U_BasicBody";
		model="\A3\characters_F\civil\c_poor";
		uniformClass="aif_uni_tig_des";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\data\aif_uni_tig_des.paa"
		};
		backpack="";
		weapons[]=
		{
			"Binocular",
			"rhs_weap_akm_gp25",
			"hgun_rook40_f",
			"Throw",
			"put"
		};
		respawnweapons[]=
		{
			"Binocular",
			"rhs_weap_akm_gp25",
			"hgun_rook40_f",
			"Throw",
			"put"
		};
		respawnmagazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_VOG25",
			"rhs_VOG25",
			"rhs_VOG25",
			"rhs_VOG25",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		magazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_VOG25",
			"rhs_VOG25",
			"rhs_VOG25",
			"rhs_VOG25",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"aif_uni_vest",
			"H_Cap_blk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"aif_uni_vest",
			"H_Cap_blk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		class EventHandlers
		{
			init="(_this select 0) execVM ""\aif_all\script\regulares.sqf""";
		};
	};
	class aif_rifleman: B_G_Soldier_F
	{
		_generalMacro="  B_G_Soldier_F ";
		scope=2;
		side=2;
		faction="usml_aif";
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_NATO",
			"NoGlasses"
		};
		faceType="Man_A3";
		genericNames="TakistaniMen";
		displayName="Rifleman";
		author="segen";
		camouflage=0.60000002;
		sensitivity=3.5;
		icon="iconMan";
		nakedUniform="U_BasicBody";
		model="\A3\characters_F\civil\c_poor";
		uniformClass="aif_uni_tig_des3";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\data\aif_uni_tig_des3.paa"
		};
		backpack="";
		weapons[]=
		{
			"Binocular",
			"rhs_weap_akm",
			"hgun_rook40_f",
			"Throw",
			"put"
		};
		respawnweapons[]=
		{
			"Binocular",
			"rhs_weap_akm",
			"hgun_rook40_f",
			"Throw",
			"put"
		};
		respawnmagazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		magazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"aif_uni_vest",
			"H_Cap_blk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"aif_uni_vest",
			"H_Cap_blk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		class EventHandlers
		{
			init="(_this select 0) execVM ""\aif_all\script\regulares.sqf""";
		};
	};
	class aif_riflemanAK103: B_G_Soldier_F
	{
		_generalMacro="  B_G_Soldier_F ";
		scope=2;
		side=2;
		faction="usml_aif";
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_NATO",
			"NoGlasses"
		};
		faceType="Man_A3";
		genericNames="TakistaniMen";
		displayName="Rifleman AK-103";
		author="segen";
		camouflage=0.60000002;
		sensitivity=3.5;
		icon="iconMan";
		nakedUniform="U_BasicBody";
		model="\A3\characters_F\civil\c_poor";
		uniformClass="aif_uni_tig_des2";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\data\aif_uni_tig_des2.paa"
		};
		backpack="";
		weapons[]=
		{
			"Binocular",
			"rhs_weap_ak103_dtk",
			"hgun_rook40_f",
			"Throw",
			"put"
		};
		respawnweapons[]=
		{
			"Binocular",
			"rhs_weap_ak103_dtk",
			"hgun_rook40_f",
			"Throw",
			"put"
		};
		respawnmagazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		magazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"aif_uni_vest",
			"H_Cap_blk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"aif_uni_vest",
			"H_Cap_blk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		class EventHandlers
		{
			init="(_this select 0) execVM ""\aif_all\script\regulares.sqf""";
		};
	};
	class aif_support_MG: B_G_Soldier_F
	{
		_generalMacro=" B_G_Soldier_F";
		scope=2;
		side=2;
		faction="usml_aif";
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_NATO",
			"NoGlasses"
		};
		faceType="Man_A3";
		genericNames="TakistaniMen";
		displayName="Machine Gunner";
		author="segen";
		icon="iconManMG";
		nakedUniform="U_BasicBody";
		model="\A3\characters_F\civil\c_poor";
		uniformClass="aif_uni_wood_w3";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\data\aif_uni_wood_w3.paa"
		};
		backpack="aif_Bag_S";
		weapons[]=
		{
			"Binocular",
			"rhs_weap_pkm",
			"hgun_rook40_f",
			"Throw",
			"put"
		};
		respawnweapons[]=
		{
			"Binocular",
			"rhs_weap_pkm",
			"hgun_rook40_f",
			"Throw",
			"put"
		};
		respawnmagazines[]=
		{
			"rhs_100Rnd_762x54mmR",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		magazines[]=
		{
			"rhs_100Rnd_762x54mmR",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"aif_uni_vest2",
			"G_Balaclava_blk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"aif_uni_vest2",
			"G_Balaclava_blk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		class EventHandlers
		{
			init="(_this select 0) execVM ""\aif_all\script\regulares.sqf""";
		};
	};
	class B_AssaultPack_blk;
	class aif_Bag_S: B_AssaultPack_blk
	{
		class TransportMagazines
		{
			class _xx_150Rnd_762x51_Box
			{
				magazine="rhs_100Rnd_762x54mmR";
				count=4;
			};
			class _xx_HandGrenade
			{
				magazine="HandGrenade";
				count=5;
			};
		};
	};
	class aif_specialist_Ex: B_G_Soldier_F
	{
		_generalMacro=" B_G_Soldier_F";
		scope=2;
		side=2;
		faction="usml_aif";
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_NATO",
			"NoGlasses"
		};
		faceType="Man_A3";
		genericNames="TakistaniMen";
		displayName="Explosive Specialist";
		author="segen";
		icon="iconManExplosive";
		nakedUniform="U_BasicBody";
		model="\A3\characters_F\civil\c_poor";
		uniformClass="aif_uni_dig_w";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\data\aif_uni_dig_w.paa"
		};
		backpack="aif_Bag_EX";
		weapons[]=
		{
			"Binocular",
			"rhs_weap_akm",
			"hgun_rook40_f",
			"Throw",
			"put"
		};
		respawnweapons[]=
		{
			"Binocular",
			"rhs_weap_akm",
			"hgun_rook40_f",
			"Throw",
			"put"
		};
		respawnmagazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		magazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"aif_uni_vest2",
			"G_Balaclava_blk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"aif_uni_vest2",
			"G_Balaclava_blk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		class EventHandlers
		{
			init="(_this select 0) execVM ""\aif_all\script\regulares.sqf""";
		};
	};
	class B_FieldPack_khk;
	class aif_Bag_EX: B_FieldPack_khk
	{
		class TransportMagazines
		{
			class _xx_DemoCharge_Remote_Mag
			{
				magazine="DemoCharge_Remote_Mag";
				count=2;
			};
			class _xx_IEDUrbanSmall_Remote_Mag
			{
				magazine="DemoCharge_Remote_Mag";
				count=1;
			};
			class _xx_SatchelCharge_Remote_Mag
			{
				magazine="SatchelCharge_Remote_Mag";
				count=1;
			};
		};
	};
	class aif_Mortar: B_G_Soldier_F
	{
		_generalMacro=" B_G_Soldier_F";
		scope=2;
		side=2;
		faction="usml_aif";
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_NATO",
			"NoGlasses"
		};
		faceType="Man_A3";
		genericNames="TakistaniMen";
		displayName="Mortar Operator";
		author="segen";
		icon="iconManExplosive";
		nakedUniform="U_BasicBody";
		model="\A3\characters_F\civil\c_poor";
		uniformClass="aif_uni_tig_w";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\data\aif_uni_tig_w.paa"
		};
		backpack="O_Mortar_01_support_F";
		weapons[]=
		{
			"Binocular",
			"rhs_weap_ak103_npz",
			"hgun_rook40_f",
			"Throw",
			"put"
		};
		respawnweapons[]=
		{
			"Binocular",
			"rhs_weap_ak103_npz",
			"hgun_rook40_f",
			"Throw",
			"put"
		};
		respawnmagazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		magazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"aif_uni_vest2",
			"G_Balaclava_blk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"aif_uni_vest2",
			"G_Balaclava_blk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		class EventHandlers
		{
			init="(_this select 0) execVM ""\aif_all\script\regulares.sqf""";
		};
	};
	class aif_riflemanGLM4: B_G_Soldier_F
	{
		_generalMacro=" B_G_Soldier_F";
		scope=2;
		side=2;
		faction="usml_aif";
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_NATO",
			"NoGlasses"
		};
		faceType="Man_A3";
		genericNames="TakistaniMen";
		displayName="Grenadier M4 M203";
		author="segen";
		icon="iconManExplosive";
		nakedUniform="U_BasicBody";
		model="\A3\characters_F\civil\c_poor";
		uniformClass="aif_uni_wood_w";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\data\aif_uni_wood_w.paa"
		};
		backpack="";
		weapons[]=
		{
			"Binocular",
			"rhs_weap_m4_m203",
			"Throw",
			"put"
		};
		respawnweapons[]=
		{
			"Binocular",
			"rhs_weap_m4_m203",
			"Throw",
			"put"
		};
		respawnmagazines[]=
		{
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"rhs_mag_M441_HE",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"aif_uni_vest2",
			"G_Balaclava_blk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"aif_uni_vest2",
			"G_Balaclava_blk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		class EventHandlers
		{
			init="(_this select 0) execVM ""\aif_all\script\regulares.sqf""";
		};
	};
	class aif_riflemanM4: B_G_Soldier_F
	{
		_generalMacro=" B_G_Soldier_F";
		scope=2;
		side=2;
		faction="usml_aif";
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_NATO",
			"NoGlasses"
		};
		faceType="Man_A3";
		genericNames="TakistaniMen";
		displayName="Rifleman M4";
		author="segen";
		icon="iconMan";
		nakedUniform="U_BasicBody";
		model="\A3\characters_F\civil\c_poor";
		uniformClass="aif_uni_dig_des2";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\data\aif_uni_dig_des2.paa"
		};
		backpack="";
		weapons[]=
		{
			"Binocular",
			"rhs_weap_m4",
			"Throw",
			"put"
		};
		respawnweapons[]=
		{
			"Binocular",
			"rhs_weap_m4",
			"Throw",
			"put"
		};
		respawnmagazines[]=
		{
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		magazines[]=
		{
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"rhs_mag_30Rnd_556x45_Mk318_Stanag",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"aif_uni_vest2",
			"G_Balaclava_blk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"aif_uni_vest2",
			"G_Balaclava_blk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		class EventHandlers
		{
			init="(_this select 0) execVM ""\aif_all\script\regulares.sqf""";
		};
	};
	class aif_Sniper: B_G_Soldier_F
	{
		_generalMacro=" B_G_Soldier_F";
		scope=2;
		side=2;
		faction="usml_aif";
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_NATO",
			"NoGlasses"
		};
		faceType="Man_A3";
		genericNames="TakistaniMen";
		displayName="Marskman";
		author="segen";
		icon="iconManRecon";
		nakedUniform="U_BasicBody";
		model="\A3\characters_F\civil\c_poor";
		uniformClass="aif_uni_dig_des";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\data\aif_uni_dig_des.paa"
		};
		backpack="";
		weapons[]=
		{
			"Binocular",
			"rhs_weap_svdp_pso1",
			"hgun_rook40_f",
			"Throw",
			"put"
		};
		respawnweapons[]=
		{
			"Binocular",
			"rhs_weap_svdp_pso1",
			"hgun_rook40_f",
			"Throw",
			"put"
		};
		respawnmagazines[]=
		{
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		magazines[]=
		{
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"rhs_10Rnd_762x54mmR_7N1",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"16Rnd_9x21_Mag",
			"HandGrenade",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		items[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"aif_uni_vest",
			"V_BandollierB_blk",
			"H_Watchcap_khk",
			"optic_SOS",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemGPS",
			"ItemRadio"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		respawnLinkedItems[]=
		{
			"aif_uni_vest",
			"V_BandollierB_blk",
			"H_Watchcap_khk",
			"optic_SOS",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemGPS",
			"ItemRadio"
		};
		class EventHandlers
		{
			init="(_this select 0) execVM ""\aif_all\script\regulares.sqf""";
		};
	};
	class I_officer_F;
	class aif_oficial3: I_officer_F
	{
		_generalMacro="  I_officer_F ";
		scope=2;
		side=2;
		faction="usml_aif";
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_NATO",
			"NoGlasses"
		};
		faceType="Man_A3";
		genericNames="TakistaniMen";
		displayName="Official Woodland";
		author="segen";
		icon="iconManOfficer";
		nakedUniform="U_BasicBody";
		uniformClass="aif_uni_officer_wood";
		hiddenSelections[]=
		{
			"camo1",
			"camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\data\aif_uni_officer_shirt3.paa",
			"aif_all\data\aif_uni_officer_pants3.paa"
		};
		backpack="";
		weapons[]=
		{
			"Binocular",
			"rhs_weap_akms_gp25",
			"Throw",
			"put"
		};
		respawnweapons[]=
		{
			"Binocular",
			"rhs_weap_akms_gp25",
			"Throw",
			"put"
		};
		respawnmagazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_VOG25",
			"rhs_VOG25",
			"rhs_VOG25",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		magazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_VOG25",
			"rhs_VOG25",
			"rhs_VOG25",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		items[]=
		{
			"FirstAidKit"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"aif_uni_vest2",
			"H_ShemagOpen_khk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"aif_uni_vest2",
			"H_ShemagOpen_khk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		class EventHandlers
		{
			init="(_this select 0) execVM ""\aif_all\script\oficiales.sqf""";
		};
	};
	class aif_oficial2: I_officer_F
	{
		_generalMacro="  I_officer_F ";
		scope=2;
		side=2;
		faction="usml_aif";
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_NATO",
			"NoGlasses"
		};
		faceType="Man_A3";
		genericNames="TakistaniMen";
		displayName="Official Urban";
		author="segen";
		icon="iconManOfficer";
		nakedUniform="U_BasicBody";
		uniformClass="aif_uni_jacket2";
		hiddenSelections[]=
		{
			"camo1",
			"camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\Data\aif_uni_officer_shirt2.paa",
			"aif_all\data\aif_uni_officer_pants2.paa"
		};
		backpack="";
		weapons[]=
		{
			"Binocular",
			"rhs_weap_akms_gp25",
			"Throw",
			"put"
		};
		respawnweapons[]=
		{
			"Binocular",
			"rhs_weap_akms_gp25",
			"Throw",
			"put"
		};
		respawnmagazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_VOG25",
			"rhs_VOG25",
			"rhs_VOG25",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		magazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_VOG25",
			"rhs_VOG25",
			"rhs_VOG25",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		items[]=
		{
			"FirstAidKit"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"aif_uni_vest2",
			"H_ShemagOpen_khk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"aif_uni_vest2",
			"H_ShemagOpen_khk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		class EventHandlers
		{
			init="(_this select 0) execVM ""\aif_all\script\oficiales.sqf""";
		};
	};
	class aif_oficial: I_officer_F
	{
		_generalMacro="  I_officer_F ";
		scope=2;
		side=2;
		faction="usml_aif";
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_NATO",
			"NoGlasses"
		};
		faceType="Man_A3";
		genericNames="TakistaniMen";
		displayName="Official Desert";
		author="segen";
		icon="iconManOfficer";
		nakedUniform="U_BasicBody";
		uniformClass="aif_uni_Jacket";
		hiddenSelections[]=
		{
			"camo1",
			"camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\Data\aif_uni_officer_shirt.paa",
			"aif_all\data\aif_uni_officer_pants.paa"
		};
		backpack="";
		weapons[]=
		{
			"Binocular",
			"rhs_weap_akms_gp25",
			"Throw",
			"put"
		};
		respawnweapons[]=
		{
			"Binocular",
			"rhs_weap_akms_gp25",
			"Throw",
			"put"
		};
		respawnmagazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_VOG25",
			"rhs_VOG25",
			"rhs_VOG25",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		magazines[]=
		{
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_30Rnd_762x39mm",
			"rhs_VOG25",
			"rhs_VOG25",
			"rhs_VOG25",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShell"
		};
		items[]=
		{
			"FirstAidKit"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		linkeditems[]=
		{
			"aif_uni_vest2",
			"H_ShemagOpen_khk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"aif_uni_vest2",
			"H_ShemagOpen_khk",
			"ItemCompass",
			"ItemMap",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		class EventHandlers
		{
			init="(_this select 0) execVM ""\aif_all\script\oficiales.sqf""";
		};
	};
	class B_G_Offroad_01_armed_F;
	class aif_armed: B_G_Offroad_01_armed_F
	{
		_generalMacro="B_G_Offroad_01_armed_F";
		scope=2;
		side=2;
		faction="usml_aif";
		displayName="Armed Pick Up";
		author="segen";
		audible=50;
		armor=100;
		armorWheels=100;
		armorEngine=2;
		hiddenSelections[]=
		{
			"camo",
			"camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\Data\aif_Armed.paa",
			"aif_all\Data\aif_Armed.paa"
		};
		typicalCargo[]=
		{
			"aif_driver"
		};
		crew="aif_driver";
		class EventHandlers
		{
			init="(_this select 0) execVM ""\aif_all\script\scripto1.sqf""";
		};
	};
	class B_G_Offroad_01_F;
	class aif_offroad: B_G_Offroad_01_F
	{
		_generalMacro="B_G_Offroad_01_F";
		scope=2;
		side=2;
		faction="usml_aif";
		displayName="Pickup [Camo]";
		author="segen";
		audible=50;
		armor=100;
		armorWheels=100;
		armorEngine=2;
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\data\aif_offroad.paa"
		};
		typicalCargo[]=
		{
			"aif_driver"
		};
		crew="aif_driver";
		class EventHandlers
		{
			init="(_this select 0) execVM ""\aif_all\script\scripto1.sqf""";
		};
	};
	class aif_offroad2: B_G_Offroad_01_F
	{
		_generalMacro="B_G_Offroad_01_F";
		scope=2;
		side=2;
		faction="usml_aif";
		displayName="Pickup [Toyota]";
		author="segen";
		audible=50;
		armor=100;
		armorWheels=100;
		armorEngine=2;
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\data\aif_offroad_2.paa"
		};
		typicalCargo[]=
		{
			"aif_driver"
		};
		crew="aif_driver";
		class EventHandlers
		{
			init="(_this select 0) execVM ""\aif_all\script\scripto1.sqf""";
		};
	};
	class rhs_btr60_msv;
	class aif_APC: rhs_btr60_msv
	{
		_generalMacro="aif_APC";
		scope=2;
		side=2;
		faction="usml_aif";
		displayName="BTR-60";
		author="segen";
		hiddenSelections[]=
		{
			"camo1",
			"camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\Data\aif_btr60_body_co.paa",
			"\rhsafrf\addons\rhs_a2port_armor\data\btr60_details_co.paa"
		};
		typicalCargo[]=
		{
			"aif_driver"
		};
		crew="aif_driver";
	};
	class rhs_t72ba_tv;
	class aif_t72b: rhs_t72ba_tv
	{
		_generalMacro="rhs_t72ba_tv";
		scope=2;
		side=2;
		faction="usml_aif";
		displayName="T-72b (1985)";
		author="segen";
		typicalCargo[]=
		{
			"aif_driver"
		};
		crew="aif_driver";
	};
	class rhs_zsu234_aa;
	class aif_zu234v: rhs_zsu234_aa
	{
		_generalMacro="rhs_zsu234_aa";
		scope=2;
		side=2;
		faction="usml_aif";
		displayName="ZSU-23 4V";
		author="segen";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\Data\aif_zsu_01_aa_co.paa",
			"aif_all\Data\aif_zsu_02_aa_co.paa",
			"aif_all\Data\aif_zsu_03_aa_co.paa"
		};
		typicalCargo[]=
		{
			"aif_driver"
		};
		crew="aif_driver";
	};
	class O_Truck_02_transport_F;
	class aif_Truck: O_Truck_02_transport_F
	{
		_generalMacro="O_Truck_02_transport_F";
		scope=2;
		side=2;
		faction="usml_aif";
		displayName="Truck";
		author="segen";
		audible=50;
		armor=100;
		armorWheels=100;
		armorEngine=2;
		hiddenSelections[]=
		{
			"camo1",
			"camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\data\body.paa",
			"aif_all\data\kuz.paa"
		};
		typicalCargo[]=
		{
			"aif_driver"
		};
		crew="aif_driver";
	};
	class RHS_Ural_VMF_01;
	class aif_truck_ural: RHS_Ural_VMF_01
	{
		_generalMacro="RHS_Ural_VMF_01";
		scope=2;
		side=2;
		faction="usml_aif";
		displayName="Ural Truck";
		author="segen";
		audible=50;
		armor=100;
		armorWheels=100;
		armorEngine=2;
		hiddenSelections[]=
		{
			"camo1",
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\Data\aif_ural_kabina_tka_co.paa",
			"aif_all\Data\aif_ural_plachta_tka_co.paa"
		};
		typicalCargo[]=
		{
			"aif_driver"
		};
		crew="aif_driver";
	};
	class O_Mortar_01_F;
	class aif_Static_mortar: O_Mortar_01_F
	{
		generalMacro="aif_Static_mortar";
		author="Segen";
		scope=2;
		side=2;
		faction="usml_aif";
		crew="aif_rifleman";
		typicalCargo[]=
		{
			"aif_rifleman"
		};
	};
	class O_static_AA_F;
	class aif_static_AA: O_static_AA_F
	{
		generalMacro="aif_static_AA";
		author="Segen";
		scope=2;
		side=2;
		faction="usml_aif";
		crew="aif_rifleman";
		typicalCargo[]=
		{
			"aif_rifleman"
		};
	};
	class O_static_AT_F;
	class aif_static_AT: O_static_AT_F
	{
		generalMacro="aif_static_AT";
		author="Segen";
		scope=2;
		side=2;
		faction="usml_aif";
		crew="aif_rifleman";
		typicalCargo[]=
		{
			"aif_rifleman"
		};
	};
	class RHS_M2StaticMG_D;
	class aif_Static_M2: RHS_M2StaticMG_D
	{
		generalMacro="aif_Static_M2";
		author="Segen";
		scope=2;
		side=2;
		faction="usml_aif";
		crew="aif_rifleman";
		typicalCargo[]=
		{
			"aif_rifleman"
		};
	};
	class RHS_M2StaticMG_MiniTripod_D;
	class aif_Static_M2_MiniTripod: RHS_M2StaticMG_MiniTripod_D
	{
		generalMacro="aif_Static_M2_MiniTripod";
		author="Segen";
		scope=2;
		side=2;
		faction="usml_aif";
		crew="aif_rifleman";
		typicalCargo[]=
		{
			"aif_rifleman"
		};
	};
	class RHS_MK19_TriPod_D;
	class aif_Static_Mk19_TriPod: RHS_MK19_TriPod_D
	{
		generalMacro="aif_Static_Mk19_TriPod";
		author="Segen";
		scope=2;
		side=2;
		faction="usml_aif";
		crew="aif_rifleman";
		typicalCargo[]=
		{
			"aif_rifleman"
		};
	};
	class SUV_01_base_f;
	class aif_car: SUV_01_base_f
	{
		_generalMacro="SUV_01_base_f";
		scope=2;
		side=2;
		faction="usml_aif";
		displayName="SUV";
		author="segen";
		audible=50;
		armor=100;
		armorWheels=100;
		armorEngine=2;
		hiddenSelections[]=
		{
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\Data\aif_suv.paa"
		};
		availableForSupportTypes[]=
		{
			"Transport"
		};
		typicalCargo[]=
		{
			"aif_rifleman"
		};
		crew="aif_rifleman";
		preferRoads=1;
		brakeDistance=7;
		class EventHandlers
		{
			init="(_this select 0) execVM ""\aif_all\script\suv.sqf""";
		};
	};
};
class cfgWeapons
{
	class ItemCore;
	class iteminfo;
	class Uniform_Base;
	class UniformItem;
	class Vest_Camo_Base;
	class vest_base;
	class VestItem;
	class HeadgearItem;
	class SportCarHorn;
	class aif_uni_tig_des3: Uniform_Base
	{
		scope=2;
		displayName="AIF Desert";
		picture="aif_all\data\icon\icon_uni.paa";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="aif_rifleman";
			containerClass="Supply40";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"aif_all\data\aif_uni_tig_des3.paa"
			};
		};
	};
	class aif_uni_tig_des2: Uniform_Base
	{
		scope=2;
		displayName="AIF Tig Des 2";
		picture="aif_all\data\icon\icon_uni.paa";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="aif_riflemanAK103";
			containerClass="Supply40";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"aif_all\data\aif_uni_tig_des2.paa"
			};
		};
	};
	class aif_uni_tig_des: Uniform_Base
	{
		scope=2;
		displayName="AIF Tig Des";
		picture="aif_all\data\icon\icon_uni.paa";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="aif_riflemanGL";
			containerClass="Supply40";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"aif_all\data\aif_uni_tig_des.paa"
			};
		};
	};
	class aif_uni_jacket: Uniform_Base
	{
		scope=2;
		displayName="AIF Oficial Des";
		picture="aif_all\data\icon\icon_uni.paa";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="aif_oficial";
			containerClass="Supply40";
			mass=40;
			hiddenSelections[]=
			{
				"camo1",
				"camo2"
			};
			hiddenSelectionsTextures[]=
			{
				"aif_all\Data\aif_uni_officer_shirt.paa",
				"aif_all\data\aif_uni_officer_pants.paa"
			};
		};
	};
	class aif_uni_officer_wood: Uniform_Base
	{
		scope=2;
		displayName="AIF Oficial Wood";
		picture="aif_all\data\icon\icon_uni.paa";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="aif_oficial3";
			containerClass="Supply40";
			mass=40;
			hiddenSelections[]=
			{
				"camo1",
				"camo2"
			};
			hiddenSelectionsTextures[]=
			{
				"aif_all\data\aif_uni_officer_shirt3.paa",
				"aif_all\data\aif_uni_officer_pants3.paa"
			};
		};
	};
	class aif_uni_jacket2: Uniform_Base
	{
		scope=2;
		displayName="AIF Oficial Urban";
		picture="aif_all\data\icon\icon_uni.paa";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="aif_oficial2";
			containerClass="Supply40";
			mass=40;
			hiddenSelections[]=
			{
				"camo1",
				"camo2"
			};
			hiddenSelectionsTextures[]=
			{
				"aif_all\Data\aif_uni_officer_shirt2.paa",
				"aif_all\data\aif_uni_officer_pants2.paa"
			};
		};
	};
	class aif_uni_dig_w: Uniform_Base
	{
		scope=2;
		displayName="AIF Digi W";
		picture="aif_all\data\icon\icon_uni.paa";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="aif_specialist_Ex";
			containerClass="Supply40";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"aif_all\data\aif_uni_dig_w.paa"
			};
		};
	};
	class aif_uni_dig_des: Uniform_Base
	{
		scope=2;
		displayName="AIF Digi Des";
		picture="aif_all\data\icon\icon_uni.paa";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="aif_sniper";
			containerClass="Supply40";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"aif_all\data\aif_uni_dig_des.paa"
			};
		};
	};
	class aif_uni_wood_w2: Uniform_Base
	{
		scope=2;
		displayName="AIF Wood W 2";
		picture="aif_all\data\icon\icon_uni.paa";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="aif_driver";
			containerClass="Supply40";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"aif_all\data\aif_uni_wood_w2.paa"
			};
		};
	};
	class aif_uni_tig_w: Uniform_Base
	{
		scope=2;
		displayName="AIF Tig W";
		picture="aif_all\data\icon\icon_uni.paa";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="aif_mortar";
			containerClass="Supply40";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"aif_all\data\aif_uni_tig_w.paa"
			};
		};
	};
	class aif_uni_tig_w2: Uniform_Base
	{
		scope=2;
		displayName="AIF Tig W 2";
		picture="aif_all\data\icon\icon_uni.paa";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="aif_support_AT";
			containerClass="Supply40";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"aif_all\data\aif_uni_tig_w2.paa"
			};
		};
	};
	class aif_uni_tig_w3: Uniform_Base
	{
		scope=2;
		displayName="AIF Tig W 3";
		picture="aif_all\data\icon\icon_uni.paa";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="aif_TeamLeader";
			containerClass="Supply40";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"aif_all\data\aif_uni_tig_w3.paa"
			};
		};
	};
	class aif_uni_wood_w: Uniform_Base
	{
		scope=2;
		displayName="AIF  Woodland W";
		picture="aif_all\data\icon\icon_uni.paa";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="aif_riflemanGLM4";
			containerClass="Supply40";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"aif_all\data\aif_uni_wood_w.paa"
			};
		};
	};
	class aif_uni_wood_w3: Uniform_Base
	{
		scope=2;
		displayName="AIF  Woodland W 3";
		picture="aif_all\data\icon\icon_uni.paa";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="aif_support_MG";
			containerClass="Supply40";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"aif_all\data\aif_uni_wood_w3.paa"
			};
		};
	};
	class aif_uni_mc: Uniform_Base
	{
		scope=2;
		displayName="AIF Multicam";
		picture="aif_all\data\icon\icon_uni.paa";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="aif_support_AA";
			containerClass="Supply40";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"aif_all\data\aif_uni_mc.paa"
			};
		};
	};
	class aif_uni_3c_des: Uniform_Base
	{
		scope=2;
		displayName="AIF 3C Des";
		picture="aif_all\data\icon\icon_uni.paa";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="aif_UAV";
			containerClass="Supply40";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"aif_all\data\aif_uni_3c_des.paa"
			};
		};
	};
	class aif_uni_3c_des2: Uniform_Base
	{
		scope=2;
		displayName="AIF 3C Des 2";
		picture="aif_all\data\icon\icon_uni.paa";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="aif_medic";
			containerClass="Supply40";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"aif_all\data\aif_uni_3c_des2.paa"
			};
		};
	};
	class aif_uni_dig_des2: Uniform_Base
	{
		scope=2;
		displayName="AIF Digi Des 2";
		picture="aif_all\data\icon\icon_uni.paa";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="aif_riflemanM4";
			containerClass="Supply40";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"aif_all\data\aif_uni_dig_des2.paa"
			};
		};
	};
	class aif_uni_dig_g: Uniform_Base
	{
		scope=2;
		displayName="AIF Digi Urban";
		picture="aif_all\data\icon\icon_uni.paa";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="aif_TeamLeader_G";
			containerClass="Supply40";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"aif_all\data\aif_uni_dig_g.paa"
			};
		};
	};
	class aif_uni_tig_g: Uniform_Base
	{
		scope=2;
		displayName="AIF Tig Urban";
		picture="aif_all\data\icon\icon_uni.paa";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="aif_medic_G";
			containerClass="Supply40";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"aif_all\data\aif_uni_tig_g.paa"
			};
		};
	};
	class aif_uni_dig_g2: Uniform_Base
	{
		scope=2;
		displayName="AIF Digi Urban 2";
		picture="aif_all\data\icon\icon_uni.paa";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="aif_rifleman_G";
			containerClass="Supply40";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"aif_all\data\aif_uni_dig_g2.paa"
			};
		};
	};
	class aif_uni_tig_g2: Uniform_Base
	{
		scope=2;
		displayName="AIF Tig Urban 2";
		picture="aif_all\data\icon\icon_uni.paa";
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="aif_support_rpg26_G";
			containerClass="Supply40";
			mass=40;
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"aif_all\data\aif_uni_tig_g2.paa"
			};
		};
	};
	class aif_uni_vest: Vest_Camo_Base
	{
		scope=2;
		displayName="AIF Vest";
		model="\A3\Characters_F_Beta\INDEP\equip_ia_vest01";
		picture="aif_all\data\icon\icon_vest.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\data\aif_uni_vest.paa"
		};
		class ItemInfo: VestItem
		{
			uniformModel="\A3\Characters_F_Beta\INDEP\equip_ia_vest01";
			containerClass="Supply100";
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"aif_all\data\aif_uni_vest.paa"
			};
		};
	};
	class aif_uni_vest2: Vest_Camo_Base
	{
		scope=2;
		displayName="AIF Vest 2";
		model="\A3\Characters_F_Beta\INDEP\equip_ia_vest01";
		picture="aif_all\data\icon\icon_vest.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"aif_all\data\aif_uni_vest2.paa"
		};
		class ItemInfo: VestItem
		{
			uniformModel="\A3\Characters_F_Beta\INDEP\equip_ia_vest01";
			containerClass="Supply100";
			hiddenSelections[]=
			{
				"camo"
			};
			hiddenSelectionsTextures[]=
			{
				"aif_all\data\aif_uni_vest2.paa"
			};
		};
	};
};
class CfgGroups
{
	class Indep
	{
		class usml_aif
		{
			name="Armed Islamic Front";
			class Infantry
			{
				name="Infantry";
				aliveCategory="Infantry";
				class aif_group_infantry_squad
				{
					name="Infantry Squad";
					faction="usml_aif";
					side=2;
					rarityGroup=0.75;
					class Unit0
					{
						side=2;
						vehicle="aif_TeamLeader";
						rank="SERGEANT";
						position[]={0,5,0};
					};
					class Unit1
					{
						side=2;
						vehicle="aif_support_MG";
						rank="SERGEANT";
						position[]={-5,0,0};
					};
					class Unit2
					{
						side=2;
						vehicle="aif_riflemanGL";
						rank="PRIVATE";
						position[]={3,0,0};
					};
					class Unit3
					{
						side=2;
						vehicle="aif_rifleman";
						rank="CORPORAL";
						position[]={5,0,0};
					};
					class Unit4
					{
						side=2;
						vehicle="aif_riflemanAK103";
						rank="PRIVATE";
						position[]={7,0,0};
					};
					class Unit5
					{
						side=2;
						vehicle="aif_support_AT";
						rank="PRIVATE";
						position[]={9,0,0};
					};
					class Unit6
					{
						side=2;
						vehicle="aif_riflemanM4";
						rank="PRIVATE";
						position[]={11,0,0};
					};
					class Unit7
					{
						side=2;
						vehicle="aif_specialist_Ex";
						rank="PRIVATE";
						position[]={13,0,0};
					};
					class Unit8
					{
						side=2;
						vehicle="aif_rifleman";
						rank="PRIVATE";
						position[]={15,0,0};
					};
					class Unit9
					{
						side=2;
						vehicle="aif_riflemanGLM4";
						rank="PRIVATE";
						position[]={17,0,0};
					};
				};
				class aif_group_fireteam
				{
					name="Fire Team";
					faction="usml_aif";
					side=2;
					rarityGroup=0.75;
					class Unit0
					{
						side=2;
						vehicle="aif_TeamLeader";
						rank="LIEUTENANT";
						position[]={0,5,0};
					};
					class Unit1
					{
						side=2;
						vehicle="aif_support_MG";
						rank="PRIVATE";
						position[]={-5,0,0};
					};
					class Unit2
					{
						side=2;
						vehicle="aif_riflemanM4";
						rank="PRIVATE";
						position[]={3,0,0};
					};
					class Unit3
					{
						side=2;
						vehicle="aif_support_AT";
						rank="PRIVATE";
						position[]={5,0,0};
					};
				};
				class aif_group_fireteam_MG
				{
					name="Fire Team MG";
					faction="usml_aif";
					side=2;
					rarityGroup=0.75;
					class Unit0
					{
						side=2;
						vehicle="aif_TeamLeader";
						rank="LIEUTENANT";
						position[]={0,5,0};
					};
					class Unit1
					{
						side=2;
						vehicle="aif_support_MG";
						rank="PRIVATE";
						position[]={-5,0,0};
					};
					class Unit2
					{
						side=2;
						vehicle="aif_support_MG";
						rank="PRIVATE";
						position[]={3,0,0};
					};
					class Unit3
					{
						side=2;
						vehicle="aif_riflemanAK103";
						rank="PRIVATE";
						position[]={5,0,0};
					};
				};
				class aif_group_fireteam_AT
				{
					name="Fire Team AT";
					faction="usml_aif";
					side=2;
					rarityGroup=0.75;
					class Unit0
					{
						side=2;
						vehicle="aif_TeamLeader";
						rank="LIEUTENANT";
						position[]={0,5,0};
					};
					class Unit1
					{
						side=2;
						vehicle="aif_support_AT";
						rank="PRIVATE";
						position[]={-5,0,0};
					};
					class Unit2
					{
						side=2;
						vehicle="aif_support_rpg26";
						rank="PRIVATE";
						position[]={3,0,0};
					};
					class Unit3
					{
						side=2;
						vehicle="aif_rifleman";
						rank="PRIVATE";
						position[]={5,0,0};
					};
				};
				class aif_group_fireteam_AA
				{
					name="Fire Team AA";
					faction="usml_aif";
					side=2;
					rarityGroup=0.75;
					class Unit0
					{
						side=2;
						vehicle="aif_TeamLeader";
						rank="LIEUTENANT";
						position[]={0,5,0};
					};
					class Unit1
					{
						side=2;
						vehicle="aif_support_AA";
						rank="PRIVATE";
						position[]={-5,0,0};
					};
					class Unit2
					{
						side=2;
						vehicle="aif_riflemanAK103";
						rank="PRIVATE";
						position[]={3,0,0};
					};
					class Unit3
					{
						side=2;
						vehicle="aif_rifleman";
						rank="PRIVATE";
						position[]={5,0,0};
					};
				};
				class aif_group_sniperteam
				{
					name="Sniper Team";
					faction="usml_aif";
					side=2;
					rarityGroup=0.75;
					class Unit0
					{
						side=2;
						vehicle="aif_sniper";
						rank="SERGEANT";
						position[]={0,5,0};
					};
					class Unit1
					{
						side=2;
						vehicle="aif_riflemanM4";
						rank="PRIVATE";
						position[]={-5,0,0};
					};
				};
				class aif_group_sentry1
				{
					name="Sentry 1";
					faction="usml_aif";
					side=2;
					rarityGroup=0.75;
					class Unit0
					{
						side=2;
						vehicle="aif_teamleader";
						rank="SERGEANT";
						position[]={0,5,0};
					};
					class Unit1
					{
						side=2;
						vehicle="aif_riflemanM4";
						rank="PRIVATE";
						position[]={-5,0,0};
					};
				};
				class aif_group_sentry2
				{
					name="Sentry 2";
					faction="usml_aif";
					side=2;
					rarityGroup=0.75;
					class Unit0
					{
						side=2;
						vehicle="aif_riflemanAK103";
						rank="SERGEANT";
						position[]={0,5,0};
					};
					class Unit1
					{
						side=2;
						vehicle="aif_riflemanGLM4";
						rank="PRIVATE";
						position[]={-5,0,0};
					};
				};
				class aif_group_fireteam_G
				{
					name="Fire Team Elite";
					faction="usml_aif";
					side=2;
					rarityGroup=0.75;
					class Unit0
					{
						side=2;
						vehicle="aif_TeamLeader_G";
						rank="LIEUTENANT";
						position[]={0,5,0};
					};
					class Unit1
					{
						side=2;
						vehicle="aif_medic_G";
						rank="PRIVATE";
						position[]={-5,0,0};
					};
					class Unit2
					{
						side=2;
						vehicle="aif_rifleman_G";
						rank="PRIVATE";
						position[]={3,0,0};
					};
					class Unit3
					{
						side=2;
						vehicle="aif_support_rpg26_G";
						rank="PRIVATE";
						position[]={5,0,0};
					};
				};
			};
			class Motorized
			{
				name="Motorized";
				aliveCategory="Motorized";
				class aif_group_patrol
				{
					name="Wheeled Patrol";
					faction="usml_aif";
					side=2;
					rarityGroup=0.75;
					class Unit0
					{
						side=2;
						vehicle="aif_TeamLeader";
						rank="LIEUTENANT";
						position[]={0,5,0};
					};
					class Unit1
					{
						side=2;
						vehicle="aif_support_MG";
						rank="PRIVATE";
						position[]={-5,0,0};
					};
					class Unit2
					{
						side=2;
						vehicle="aif_support_AT";
						rank="PRIVATE";
						position[]={3,0,0};
					};
					class Unit3
					{
						side=2;
						vehicle="aif_rifleman";
						rank="PRIVATE";
						position[]={5,0,0};
					};
					class Unit4
					{
						side=2;
						vehicle="aif_armed";
						rank="PRIVATE";
						position[]={7,0,0};
					};
				};
				class aif_transport_group
				{
					name="Troop Transport";
					faction="usml_aif";
					side=2;
					rarityGroup=0.75;
					class Unit0
					{
						side=2;
						vehicle="aif_TeamLeader";
						rank="SERGEANT";
						position[]={0,5,0};
					};
					class Unit1
					{
						side=2;
						vehicle="aif_support_MG";
						rank="SERGEANT";
						position[]={-5,0,0};
					};
					class Unit2
					{
						side=2;
						vehicle="aif_riflemanGL";
						rank="PRIVATE";
						position[]={3,0,0};
					};
					class Unit3
					{
						side=2;
						vehicle="aif_rifleman";
						rank="CORPORAL";
						position[]={5,0,0};
					};
					class Unit4
					{
						side=2;
						vehicle="aif_riflemanAK103";
						rank="PRIVATE";
						position[]={7,0,0};
					};
					class Unit5
					{
						side=2;
						vehicle="aif_support_AT";
						rank="PRIVATE";
						position[]={9,0,0};
					};
					class Unit6
					{
						side=2;
						vehicle="aif_riflemanGLM4";
						rank="PRIVATE";
						position[]={11,0,0};
					};
					class Unit7
					{
						side=2;
						vehicle="aif_specialist_Ex";
						rank="PRIVATE";
						position[]={13,0,0};
					};
					class Unit8
					{
						side=2;
						vehicle="aif_riflemanM4";
						rank="PRIVATE";
						position[]={15,0,0};
					};
					class Unit9
					{
						side=2;
						vehicle="aif_truck";
						rank="PRIVATE";
						position[]={17,0,0};
					};
				};
				class aif_group_technicals
				{
					name="Armed Pick Up Patrol";
					faction="usml_aif";
					side=2;
					rarityGroup=0.75;
					class Unit0
					{
						side=2;
						vehicle="aif_armed";
						rank="LIEUTENANT";
						position[]={0,5,0};
					};
					class Unit1
					{
						side=2;
						vehicle="aif_armed";
						rank="PRIVATE";
						position[]={-5,0,0};
					};
					class Unit2
					{
						side=2;
						vehicle="aif_offroad2";
						rank="PRIVATE";
						position[]={3,0,0};
					};
				};
			};
			class Mechanized
			{
				name="Mechanized";
				aliveCategory="Mechanized";
				class aif_group_mechanized_squad
				{
					name="BTR-60 Squad";
					faction="usml_aif";
					side=2;
					rarityGroup=0.75;
					class Unit0
					{
						side=2;
						vehicle="aif_TeamLeader";
						rank="SERGEANT";
						position[]={-5,0,0};
					};
					class Unit1
					{
						side=2;
						vehicle="aif_riflemanM4";
						rank="PRIVATE";
						position[]={3,0,0};
					};
					class Unit2
					{
						side=2;
						vehicle="aif_rifleman";
						rank="CORPORAL";
						position[]={5,0,0};
					};
					class Unit3
					{
						side=2;
						vehicle="aif_support_MG";
						rank="PRIVATE";
						position[]={7,0,0};
					};
					class Unit4
					{
						side=2;
						vehicle="aif_support_rpg26";
						rank="PRIVATE";
						position[]={9,0,0};
					};
					class Unit5
					{
						side=2;
						vehicle="aif_support_MG";
						rank="PRIVATE";
						position[]={11,0,0};
					};
					class Unit6
					{
						side=2;
						vehicle="aif_riflemanGLM4";
						rank="PRIVATE";
						position[]={13,0,0};
					};
					class Unit7
					{
						side=2;
						vehicle="aif_apc";
						rank="PRIVATE";
						position[]={15,0,0};
					};
				};
			};
			class Armored
			{
				name="Armored";
				aliveCategory="Armored";
				class aif_group_T72_x2
				{
					name="T-72b x2";
					faction="usml_aif";
					side=2;
					rarityGroup=0.75;
					class Unit0
					{
						side=2;
						vehicle="aif_t72b";
						rank="SERGEANT";
						position[]={0,5,0};
					};
					class Unit1
					{
						side=2;
						vehicle="aif_t72b";
						rank="PRIVATE";
						position[]={-5,0,0};
					};
				};
				class aif_group_T72_inf
				{
					name="T-72b Infantry";
					faction="usml_aif";
					side=2;
					rarityGroup=0.75;
					class Unit0
					{
						side=2;
						vehicle="aif_TeamLeader";
						rank="LIEUTENANT";
						position[]={0,5,0};
					};
					class Unit1
					{
						side=2;
						vehicle="aif_support_MG";
						rank="PRIVATE";
						position[]={-5,0,0};
					};
					class Unit2
					{
						side=2;
						vehicle="aif_support_AT";
						rank="PRIVATE";
						position[]={3,0,0};
					};
					class Unit3
					{
						side=2;
						vehicle="aif_rifleman";
						rank="PRIVATE";
						position[]={5,0,0};
					};
					class Unit4
					{
						side=2;
						vehicle="aif_t72b";
						rank="PRIVATE";
						position[]={7,0,0};
					};
				};
				class aif_group_zu23
				{
					name="ZU-23";
					faction="usml_aif";
					side=2;
					rarityGroup=0.75;
					class Unit0
					{
						side=2;
						vehicle="aif_zu234v";
						rank="SERGEANT";
						position[]={0,5,0};
					};
				};
			};
			class Support
			{
				name="Support";
				aliveCategory="Support";
				class aif_group_mortarteam
				{
					name="Mortar Team";
					faction="usml_aif";
					side=2;
					rarityGroup=0.75;
					class Unit0
					{
						side=2;
						vehicle="aif_mortar";
						rank="SERGEANT";
						position[]={0,5,0};
					};
					class Unit1
					{
						side=2;
						vehicle="aif_rifleman";
						rank="PRIVATE";
						position[]={-5,0,0};
					};
					class Unit2
					{
						side=2;
						vehicle="aif_UAV";
						rank="PRIVATE";
						position[]={3,0,0};
					};
				};
			};
		};
	};
};
